junit:
  stage: test
  script:
    - mvn -B clean test -Dtest=\*Test

generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean package -DskipTests
  artifacts:
    paths:
      - target/journey*.jar
